language: cpp

sudo: false

os:
    - osx
    - linux

compiler: gcc

before_install: ./CI/travis.before_install.sh
install: ./CI/travis.install.sh

before_script:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi

script:
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=ci_dist/ .
    - make
    - make install

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GXh1fTaMgGL2HKKRtPQ9BICrrk9UPV0Ho5QEhW4UNd3qn1UIJ1wIxTt/pX/3uYzwoQQr4aV/VVS1L3trk9Nv6658NHsrr8JeN/5xTgi4xjiyEmLA+1oXpmsD+7PatM9P7wNP7w2Ucy0dF2E6V2esZvghrEobyk1asF5siAgwXRc="

addons:
  coverity_scan:
    project:
      name: "mattiascibien/ivygen"
      description: "<Your project description here>"
    notification_email: mattias@mattiascibien.net
    build_command_prepend: "cmake -DCMAKE_INSTALL_PREFIX:PATH=ci_dist/ ."
    build_command:   "make"
    branch_pattern: coverity_scan
  apt:
    sources:
      - ubuntu-sdk-team
      - george-edison55-precise-backports
    packages:
      - cmake-data 
      - cmake
      - qtbase5-dev