language: cpp
dist: trusty

sudo: false

os:
    - osx
    - linux

compiler: gcc

before_install: ./CI/travis.before_install.sh
install: ./CI/travis.install.sh

before_script:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi

script:
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=ci_dist/ .
    - make
    - make install
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake -G DEB -C Release

addons:
  apt:
    sources:
      - ubuntu-sdk-team
      - george-edison55-precise-backports
    packages:
      - cmake-data 
      - cmake
      - qtbase5-dev
      - libqt5opengl5-dev
      
      
