language: cpp

compiler: gcc

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev

script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
    - make install

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GXh1fTaMgGL2HKKRtPQ9BICrrk9UPV0Ho5QEhW4UNd3qn1UIJ1wIxTt/pX/3uYzwoQQr4aV/VVS1L3trk9Nv6658NHsrr8JeN/5xTgi4xjiyEmLA+1oXpmsD+7PatM9P7wNP7w2Ucy0dF2E6V2esZvghrEobyk1asF5siAgwXRc="

addons:
  coverity_scan:
    project:
      name: "mattiascibien/ivygen"
      description: "<Your project description here>"
    notification_email: mattias@mattiascibien.net
    build_command_prepend: "qmake -qt=qt5"
    build_command:   "make"
    branch_pattern: coverity_scan
