install:
  - set QTDIR=C:\Qt\5.5\msvc2013
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
build_script:
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=ci_dist/ . -G "NMake Makefiles"
  - nmake
